name: Lint
on:
  push:
    branches:
    - master

jobs:
  lint:
    strategy:
      matrix:
        go: ['1.13', '1.14']

    name: Lint with Go ${{ matrix.go }}
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run Lint
      run: golint -set_exit_status ./...
