name: Lint
on:
  push:
    branches:
    - main

jobs:
  lint:
    strategy:
      matrix:
        go: ['1.24', '1.25']

    name: Lint | Go ${{ matrix.go }}
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Run Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1
